name: ICAI Batch Checker

on:
  schedule:
    - cron: "*/5 1-17 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium requests
          sudo apt-get update
          sudo apt-get install -y firefox
          sudo apt-get install -y firefox-geckodriver

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python linux.py
